table 'Spotify Dataset'
	lineageTag: 7abb9b7c-933a-452d-bc96-e3a077873e84

	measure MaxStreams = MAX('Spotify Dataset'[streams])
		formatString: 0
		lineageTag: 58df7b71-21ea-467b-8be9-b2b3884a712e

	measure _EnergyPercentage = AVERAGE('Spotify Dataset'[energy_%])
		lineageTag: c4f04e8b-850f-4cc9-adcc-32261215f63a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _TrackCount = COUNT('Spotify Dataset'[track_name])
		formatString: 0
		lineageTag: 60603fbb-5465-408a-b8d0-a5269d655c57

	column track_name
		dataType: string
		lineageTag: 33792293-b47c-49f0-859f-c672532e5431
		summarizeBy: none
		sourceColumn: track_name

		annotation SummarizationSetBy = Automatic

	column artist(s)_name
		dataType: string
		lineageTag: 0fbe4647-aede-4054-927f-79ae048d7500
		summarizeBy: none
		sourceColumn: artist(s)_name

		annotation SummarizationSetBy = Automatic

	column artist_count
		dataType: int64
		formatString: 0
		lineageTag: 0852d3e4-7bfe-4aaf-bc26-fb439870b147
		summarizeBy: sum
		sourceColumn: artist_count

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: f9378ffb-e56c-42ea-9279-7c294086c69b
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column in_spotify_playlists
		dataType: int64
		formatString: 0
		lineageTag: 7cb0e755-e5aa-46f9-a435-cee6716c7ed3
		summarizeBy: sum
		sourceColumn: in_spotify_playlists

		annotation SummarizationSetBy = Automatic

	column in_spotify_charts
		dataType: int64
		formatString: 0
		lineageTag: d3d594b5-9c62-4b1a-84b1-63b2e4dc9d96
		summarizeBy: sum
		sourceColumn: in_spotify_charts

		annotation SummarizationSetBy = Automatic

	column streams
		dataType: int64
		formatString: 0
		lineageTag: bf7be4a0-7848-44d4-b4f3-7f725a2b9c09
		summarizeBy: sum
		sourceColumn: streams

		annotation SummarizationSetBy = Automatic

	column in_apple_playlists
		dataType: int64
		formatString: 0
		lineageTag: 72d842bb-e594-4c25-9c96-502d72288578
		summarizeBy: sum
		sourceColumn: in_apple_playlists

		annotation SummarizationSetBy = Automatic

	column in_apple_charts
		dataType: int64
		formatString: 0
		lineageTag: 553d4f90-66d7-429d-b804-fbe927de3801
		summarizeBy: sum
		sourceColumn: in_apple_charts

		annotation SummarizationSetBy = Automatic

	column in_deezer_playlists
		dataType: int64
		formatString: 0
		lineageTag: 12ce7f4d-11b4-474b-8a48-fdcc11a3cc64
		summarizeBy: sum
		sourceColumn: in_deezer_playlists

		annotation SummarizationSetBy = Automatic

	column in_deezer_charts
		dataType: int64
		formatString: 0
		lineageTag: dc09b15e-1af2-4eed-9b84-dd0aa37b215e
		summarizeBy: sum
		sourceColumn: in_deezer_charts

		annotation SummarizationSetBy = Automatic

	column in_shazam_charts
		dataType: double
		lineageTag: c2b56927-8484-4464-af52-6ad4536b4ca7
		summarizeBy: sum
		sourceColumn: in_shazam_charts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bpm
		dataType: int64
		formatString: 0
		lineageTag: c74b5a26-cba7-40e7-b37a-7798d7022848
		summarizeBy: sum
		sourceColumn: bpm

		annotation SummarizationSetBy = Automatic

	column key
		dataType: string
		lineageTag: add56fa4-cdf5-4c80-80b8-34cf850e7364
		summarizeBy: none
		sourceColumn: key

		annotation SummarizationSetBy = Automatic

	column mode
		dataType: string
		lineageTag: 1287c5a8-8c24-4dff-91ab-ddd05fcd4b86
		summarizeBy: none
		sourceColumn: mode

		annotation SummarizationSetBy = Automatic

	column danceability_%
		dataType: int64
		formatString: 0
		lineageTag: 67bfcf70-d8cb-402f-ad65-1f2c87e976f9
		summarizeBy: sum
		sourceColumn: danceability_%

		annotation SummarizationSetBy = Automatic

	column valence_%
		dataType: int64
		formatString: 0
		lineageTag: c05576d0-afe0-4ffd-8448-b475ebffebce
		summarizeBy: sum
		sourceColumn: valence_%

		annotation SummarizationSetBy = Automatic

	column energy_%
		dataType: int64
		formatString: 0
		lineageTag: c267f01d-3975-44f0-aab0-444423f99f0d
		summarizeBy: sum
		sourceColumn: energy_%

		annotation SummarizationSetBy = Automatic

	column acousticness_%
		dataType: int64
		formatString: 0
		lineageTag: a8f8604b-7d67-447b-94fe-c020facfb5b8
		summarizeBy: sum
		sourceColumn: acousticness_%

		annotation SummarizationSetBy = Automatic

	column instrumentalness_%
		dataType: int64
		formatString: 0
		lineageTag: 9d50bb65-507a-4293-9e41-0fa5d3706435
		summarizeBy: sum
		sourceColumn: instrumentalness_%

		annotation SummarizationSetBy = Automatic

	column liveness_%
		dataType: int64
		formatString: 0
		lineageTag: 652d4cc4-bc7d-49c7-97b6-02491a53c844
		summarizeBy: sum
		sourceColumn: liveness_%

		annotation SummarizationSetBy = Automatic

	column speechiness_%
		dataType: int64
		formatString: 0
		lineageTag: 369e3619-0e8f-4969-95c3-f30b51930dfe
		summarizeBy: sum
		sourceColumn: speechiness_%

		annotation SummarizationSetBy = Automatic

	column cover_url
		dataType: string
		lineageTag: 098adf47-14a0-4a68-b908-a729f7f38120
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: cover_url

		annotation SummarizationSetBy = Automatic

	partition 'Spotify Dataset' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI\Spotify\Spotify Most Streamed Songs 2023 Dataset.xlsx"), null, true),
				    #"Spotify Dataset_Sheet" = Source{[Item="Spotify Dataset",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Spotify Dataset_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"track_name", type any}, {"artist(s)_name", type text}, {"artist_count", Int64.Type}, {"released_year", Int64.Type}, {"released_month", Int64.Type}, {"released_day", Int64.Type}, {"in_spotify_playlists", Int64.Type}, {"in_spotify_charts", Int64.Type}, {"streams", Int64.Type}, {"in_apple_playlists", Int64.Type}, {"in_apple_charts", Int64.Type}, {"in_deezer_playlists", Int64.Type}, {"in_deezer_charts", Int64.Type}, {"in_shazam_charts", Int64.Type}, {"bpm", Int64.Type}, {"key", type text}, {"mode", type text}, {"danceability_%", Int64.Type}, {"valence_%", Int64.Type}, {"energy_%", Int64.Type}, {"acousticness_%", Int64.Type}, {"instrumentalness_%", Int64.Type}, {"liveness_%", Int64.Type}, {"speechiness_%", Int64.Type}, {"cover_url", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"streams"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Errors",null,"None",Replacer.ReplaceValue,{"key"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"in_shazam_charts"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Replaced Value1", "Merged", each Text.Combine({Text.From([released_month], "en-US"), "/", Text.From([released_day], "en-US"), "/", Text.From([released_year], "en-US")}), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "Date"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"track_name", "artist(s)_name", "artist_count", "Date", "released_year", "released_month", "released_day", "in_spotify_playlists", "in_spotify_charts", "streams", "in_apple_playlists", "in_apple_charts", "in_deezer_playlists", "in_deezer_charts", "in_shazam_charts", "bpm", "key", "mode", "danceability_%", "valence_%", "energy_%", "acousticness_%", "instrumentalness_%", "liveness_%", "speechiness_%", "cover_url"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"released_year", "released_month", "released_day"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

